

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvideWithNavigate from "@/authServices/AuthProvideWithNavigate";
import Providers from "@/queryClientProvider/clientInitialization";
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
   
      <body className={inter.className}>
  
      <Providers>
  <AuthProvideWithNavigate>
        {children}
        </AuthProvideWithNavigate>
        </Providers>
        <Toaster visibleToasts={1} position="top-right" richColors />
        </body>
        
    
    </html>
  );
}
